# Generated by Django 3.2.8 on 2021-11-24 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_english', models.CharField(max_length=70)),
                ('name_bangla', models.CharField(max_length=70)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/assets/images/categories_image')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='static/assets/images/categories_icon')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_english', models.CharField(max_length=70)),
                ('name_bangla', models.CharField(max_length=70)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/assets/images/categories_image')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='static/assets/images/categories_icon')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.categories')),
            ],
        ),
    ]
