# Generated by Django 3.2.8 on 2021-11-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('name_english', models.CharField(max_length=50)),
                ('name_bangla', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/assets/images/categories_image')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='static/assets/images/categories_icon')),
            ],
        ),
    ]
