# Generated by Django 3.2.8 on 2021-11-25 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='update_at',
        ),
    ]
