# Generated by Django 3.2.8 on 2021-11-25 05:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20211125_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 11, 25, 5, 55, 8, 26368, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categories',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
