# Generated by Django 3.2.8 on 2021-11-25 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_auto_20211125_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategories_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_english', models.CharField(max_length=70)),
                ('name_bangla', models.CharField(max_length=70)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/assets/images/categories_image')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='static/assets/images/categories_icon')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.categories')),
            ],
        ),
    ]
