# Generated by Django 3.2.8 on 2021-11-30 12:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_alter_subcategories_2_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='create_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='categories',
            old_name='update_at',
            new_name='updated',
        ),
        migrations.AddField(
            model_name='subcategories',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategories',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='subcategories_2',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategories_2',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
