# Generated by Django 3.2.8 on 2021-12-02 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_auto_20211130_1826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategories_2',
            old_name='category',
            new_name='subcategory',
        ),
    ]
