# Generated by Django 3.2.8 on 2021-12-02 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0008_alter_subcategories_2_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategories_2',
            name='subcategory',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='categories.subcategories'),
            preserve_default=False,
        ),
    ]
