# Generated by Django 3.2.8 on 2021-12-22 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20211222_1520'),
        ('categories', '0010_alter_subcategories_2_subcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubCategories_2',
        ),
    ]
