# Generated by Django 3.2.8 on 2021-11-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=50)),
                ('iso_code2', models.CharField(max_length=20)),
                ('iso_code3', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TaxClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('descriptiom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TaxRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_class', models.CharField(max_length=100)),
                ('zone', models.CharField(max_length=50)),
                ('tax_rate', models.IntegerField(max_length=50)),
                ('descriptiom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Zones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('country_name', models.CharField(max_length=50)),
                ('country_code', models.IntegerField(max_length=50)),
            ],
        ),
    ]
