# Generated by Django 3.2.8 on 2021-11-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_location', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxrates',
            name='tax_rate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='zones',
            name='country_code',
            field=models.IntegerField(),
        ),
    ]
