# Generated by Django 3.2.8 on 2021-11-30 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_location', '0003_rename_descriptiom_taxclasses_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxclasses',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='taxclasses',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
