# Generated by Django 3.2.8 on 2021-11-30 12:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tax_location', '0004_auto_20211130_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxclasses',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taxclasses',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
