# Generated by Django 3.2.8 on 2021-12-06 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tax_location', '0006_auto_20211206_0125'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Countries',
        ),
        migrations.DeleteModel(
            name='Zones',
        ),
        migrations.RenameField(
            model_name='taxrates',
            old_name='descriptiom',
            new_name='description',
        ),
    ]
