# Generated by Django 3.2.8 on 2021-12-06 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tax_location', '0007_auto_20211206_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxclasses',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taxrates',
            name='tax_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tax_location.taxclasses'),
        ),
    ]
