# Generated by Django 3.2.8 on 2021-12-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_location', '0008_auto_20211206_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxclasses',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
