# Generated by Django 3.2.8 on 2021-12-06 10:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tax_location', '0009_alter_taxclasses_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxclasses',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
