# Generated by Django 3.2.8 on 2021-12-06 11:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tax_location', '0011_alter_taxclasses_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxrates',
            name='category',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='tax_location.taxclasses'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taxrates',
            name='tax_class',
            field=models.CharField(max_length=50),
        ),
    ]
