# Generated by Django 3.2.8 on 2021-12-06 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tax_location', '0013_merge_0012_auto_20211206_1742_0012_auto_20211206_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taxrates',
            old_name='category',
            new_name='tax_classes',
        ),
    ]
