# Generated by Django 3.2.8 on 2021-11-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('title_new_english', models.CharField(max_length=20)),
                ('description_english', models.CharField(max_length=20)),
                ('title_new_bangla', models.CharField(max_length=20)),
                ('description_bangla', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/assets/images/news_images')),
                ('is_feature', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NewsCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_english', models.CharField(max_length=100)),
                ('name_bangla', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/assets/images/news_images')),
            ],
        ),
    ]
