# Generated by Django 3.2.8 on 2021-11-23 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20211123_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newscategories',
            name='added_last_modified_date',
        ),
    ]
