# Generated by Django 3.2.8 on 2021-12-01 05:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_remove_newscategories_added_last_modified_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscategories',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newscategories',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
