# Generated by Django 3.2.8 on 2021-11-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('coupon_type', models.CharField(max_length=50)),
                ('discount_type', models.CharField(max_length=50)),
                ('coupon_ammount', models.IntegerField(max_length=50)),
                ('minimum_spend', models.IntegerField(max_length=50)),
                ('coupon_quantity_limit', models.IntegerField(max_length=50)),
                ('products', models.CharField(max_length=500)),
                ('exclude_products', models.CharField(max_length=500)),
                ('usage_limit_per_coupon', models.IntegerField(max_length=50)),
                ('usage_limit_per_user', models.IntegerField(max_length=50)),
            ],
        ),
    ]
