# Generated by Django 3.2.8 on 2021-11-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupons',
            name='coupon_ammount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='coupons',
            name='coupon_quantity_limit',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='coupons',
            name='minimum_spend',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='coupons',
            name='usage_limit_per_coupon',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='coupons',
            name='usage_limit_per_user',
            field=models.IntegerField(),
        ),
    ]
