# Generated by Django 3.2.8 on 2021-11-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devices', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=20)),
                ('message', models.TextField(max_length=100)),
                ('image_link', models.URLField()),
            ],
        ),
    ]
