# Generated by Django 3.2.8 on 2021-11-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('manufacturer_url', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/assets/images/manufacture_images')),
            ],
        ),
    ]
