# Generated by Django 3.2.8 on 2021-11-30 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturer', '0002_auto_20211129_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/assets/images/manufacture_images'),
        ),
    ]
