# Generated by Django 3.2.8 on 2021-12-01 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturer', '0004_alter_manufacturer_manufacturer_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/media/manufacture_images'),
        ),
    ]
