# Generated by Django 3.2.8 on 2021-11-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('sub_category', models.CharField(max_length=20)),
                ('manufacturars', models.CharField(max_length=50)),
                ('special', models.CharField(max_length=20)),
                ('product_name_english', models.CharField(max_length=50)),
                ('description_english', models.CharField(max_length=50)),
                ('product_name_bangla', models.CharField(max_length=20)),
                ('description_bangla', models.CharField(max_length=50)),
                ('tax_class', models.CharField(max_length=50)),
                ('product_price', models.IntegerField(max_length=20)),
                ('products_quantity', models.IntegerField(max_length=100)),
                ('offer_quantity_limit', models.IntegerField(max_length=100)),
                ('quantity_low_limit', models.IntegerField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/assets/images/products_image')),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_options_english', models.CharField(max_length=50)),
                ('add_options_bangla', models.CharField(max_length=20)),
            ],
        ),
    ]
