# Generated by Django 3.2.8 on 2021-11-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='offer_quantity_limit',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='products_quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity_low_limit',
            field=models.IntegerField(),
        ),
    ]
