# Generated by Django 3.2.8 on 2021-12-02 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0010_alter_subcategories_2_subcategory'),
        ('products', '0005_auto_20211130_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subcategory_2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='categories.subcategories_2'),
            preserve_default=False,
        ),
    ]
