# Generated by Django 3.2.8 on 2021-12-02 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0010_alter_subcategories_2_subcategory'),
        ('products', '0006_product_subcategory_2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sub_category',
            new_name='subcategory',
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory_2',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='categories.subcategories_2'),
        ),
    ]
