# Generated by Django 3.2.8 on 2021-12-02 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0010_alter_subcategories_2_subcategory'),
        ('products', '0007_auto_20211202_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.subcategories'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.subcategories_2'),
        ),
    ]
