# Generated by Django 3.2.8 on 2021-12-22 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20211202_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='product',
            name='subcategory_2',
        ),
        migrations.DeleteModel(
            name='ProductAttributes',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
