# Generated by Django 3.2.8 on 2021-12-22 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0011_delete_subcategories_2'),
        ('store', '0003_auto_20211222_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='categories.categories'),
            preserve_default=False,
        ),
    ]
