# Generated by Django 3.2.8 on 2021-12-29 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20211229_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='conf_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='telephone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
