# Generated by Django 3.2.8 on 2021-11-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='telephone',
            field=models.IntegerField(),
        ),
    ]
