# Generated by Django 3.2.8 on 2021-12-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customers_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
