# Generated by Django 3.2.8 on 2021-12-29 10:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20211201_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='fax',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='status',
        ),
        migrations.AddField(
            model_name='customers',
            name='conf_password',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customers',
            name='username',
            field=models.CharField(default='shohag', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customers',
            name='email_address',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='customers',
            name='first_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='customers',
            name='last_name',
            field=models.CharField(max_length=200),
        ),
    ]
