# Generated by Django 3.2.8 on 2021-12-01 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='slug',
        ),
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/assets/images/brand'),
        ),
        migrations.DeleteModel(
            name='BrandImages',
        ),
    ]
