# Generated by Django 3.2.8 on 2021-12-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special_product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='special_product',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
