# Generated by Django 3.2.8 on 2021-12-07 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_pages_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=50),
        ),
    ]
