# Generated by Django 3.2.8 on 2021-11-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_methods', models.CharField(max_length=50)),
                ('braintree_account_type', models.CharField(max_length=20)),
                ('braintree', models.CharField(max_length=20)),
                ('marchant_id', models.CharField(max_length=50)),
                ('private_key', models.CharField(max_length=20)),
                ('public_key', models.CharField(max_length=20)),
                ('stripe_environment', models.CharField(max_length=20)),
                ('stripe', models.CharField(max_length=20)),
                ('secret_key', models.CharField(max_length=20)),
                ('key', models.CharField(max_length=20)),
                ('paypal_environment', models.CharField(max_length=20)),
                ('paypal', models.CharField(max_length=20)),
                ('paypal_id', models.CharField(max_length=20)),
                ('cash_on_delivary', models.CharField(max_length=20)),
                ('payment_in_currency', models.CharField(max_length=20)),
            ],
        ),
    ]
