# Generated by Django 3.2.8 on 2021-11-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='packagestype',
            name='cashback',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='packagestype',
            name='monthly_target',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='packagestype',
            name='nb_card_limit',
            field=models.IntegerField(),
        ),
    ]
