# Generated by Django 3.2.8 on 2021-11-08 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=20)),
                ('direction', models.CharField(max_length=50)),
                ('icon', models.ImageField(upload_to='static/assets/images/language_icons')),
                ('directory', models.CharField(max_length=100)),
            ],
        ),
    ]
