# Generated by Django 3.2.8 on 2021-11-08 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languages',
            name='direction',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='languages',
            name='directory',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='languages',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='static/assets/images/language_icons'),
        ),
    ]
