# Generated by Django 3.2.8 on 2021-11-08 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0002_auto_20211108_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='languages',
            name='direction',
        ),
    ]
